### ISSUE TITLE
Not working for https sites.

### ISSUE THREAD

**Issue by tfnigel** [newfolder0/chrome-clacks#10]
Well I've only tried one (my own) https://atkinson.kiwi.nz
I can confirm the header is being sent, as I can see it using the developer tools. Perhaps there are some new chrome security things stopping the script for seeing the headers, or perhaps running at all.
http works fine.

**Comment by tfnigel** [comment]
Ignore me for now, unless others are seeing this - refreshing seems to activate this script. Perhaps there is something weird with my site.

**Comment by newfolder0** [comment]
Finally got around to logging into Github and looking at this... I've just merged others suggested updates to make it work the the newer versions of Chrome. Your website seems to be showing it right now!
