### ISSUE TITLE
Improvement for popup.js

### ISSUE THREAD

**Issue by Ryuno-Ki** [newfolder0/chrome-clacks#4]
Regarding line https://github.com/newfolder0/chrome-clacks/blob/03020050e7107bce48aaf8604bc7f5f7a153d194/src/popup.js#L15 I would prefer [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) over innerHTML.

Otherwise you may run into trouble if `responseHeaders` is crafted with HTML inside (think JavaScript). I'm not that familiar with HTTP-Headers, though.

**Comment by newfolder0** [comment]
That's a good point, headers formatted as html (though unlikely) would make a mess of things. I'll have a look into it. Thanks :).

**Comment by newfolder0** [comment]
That's a good point, headers formatted as html (though unlikely) would make a mess of things. Perfect, implemented. Thanks a lot!
