### ISSUE TITLE
Firefox Add-On?

### ISSUE THREAD

**Issue by Ryuno-Ki** [newfolder0/chrome-clacks#5]
Is there any idea/motivation for a Firefox AddOn?

Would be my first, if nobody wants to take it …

**Comment by newfolder0** [comment]
Someone has posted the following on reddit.com/r/GNUTerryPratchett but I don't use Firefox so I haven't tested it myself:

https://addons.mozilla.org/en-US/firefox/addon/gnu_terry_pratchett/

I don't know anything about Firefox development, but then I didn't really know about Chrome dev before I tried this. My original motivation for this was really just for my own use (I use Chrome) and I released it after seeing how much interest there was!

Edit: I suppose I'll close the issue, I don't think that'll keep you from commenting again if you have anything else to add.
