### ISSUE TITLE
Icon moved to menu in new chrome

### ISSUE THREAD

**Issue by g0ddest** [newfolder0/chrome-clacks#9]
After chrome update icon moved from address line to menu as icon

**Comment by newfolder0** [comment]
Thanks for letting me know :). I haven't been using Chrome as much recently but mine doesn't seem to have updated yet. If you have time, a screenshot or something would be awesome. Otherwise I can update and try to check it out in the next couple of weeks.

**Comment by g0ddest** [comment]
![image](https://cloud.githubusercontent.com/assets/831951/13918862/993bb072-ef72-11e5-9cfc-22efc078d6a0.png)
Formally it was in address line and it was better.

**Comment by newfolder0** [comment]
Perfect, thank you very much! Huh. That's weird, I haven't changed anything. I originally placed it in the address line so it would be hidden when the clacks weren't present. I'll investigate what has changed when I can find the time, thanks for letting me know!

**Comment by newfolder0** [comment]
https://groups.google.com/a/chromium.org/forum/#!searchin/chromium-extensions/upcoming/chromium-extensions/7As9MKhav5E/dNiZDoSCCQAJ

Looks like it's a permanent update to that way pageAction icons are shown in Chrome. A poorly thought out change if you ask me, as it makes pageAction functionality not much different from a normal icon and clogs up the UI. The only thing you can do is drag it into the 'hamburger menu' (three horizontal lines menu icon) but then you will never see it unless you go looking for it. It is particularly bad for 'novelty' extensions like this one; if I was an average user with Chrome, this would be annoying enough to make me uninstall the extension.

Funnily enough I've been using Firefox for a while now, along with someone else's extension to provide the same functionality. They keep adding stuff like this and it has ultimately pushed me away from the browser.

**Comment by g0ddest** [comment]
Thank you for your response. Its pretty annoying really. So sorry that we cant do anything.

**Comment by newfolder0** [comment]
Agreed. Thanks again for getting involved :).
